apiVersion: v1
kind: Namespace
metadata:
  name: clarena
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: clarena
data:
  USER_KEY: "mi_usuario"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: clarena
type: Opaque
data:
  BD_PASSWORD: bXlfcGFzc3dvcmQ=  # base64 de "my_password"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: curso-devops-app
  namespace: clarena
spec:
  replicas: 3
  selector:
    matchLabels:
      app: curso-devops
  template:
    metadata:
      labels:
        app: curso-devops
    spec:
      containers:
        - name: curso-devops-container
          image: curso-devops-lab3:local
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: USER_KEY
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: USER_KEY
            - name: BD_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: BD_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: curso-devops-service
  namespace: clarena
spec:
  type: NodePort
  selector:
    app: curso-devops
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000