sonar.projectKey=curso-devops-lab3
sonar.projectName=curso-devops-lab3
sonar.projectVersion=0.0.1

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8